# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_store.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62ook_store.proto\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\")\n\x08NodeInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"F\n\tChainNode\x12\x17\n\x04node\x18\x01 \x01(\x0b\x32\t.NodeInfo\x12\x0f\n\x07is_head\x18\x02 \x01(\x08\x12\x0f\n\x07is_tail\x18\x03 \x01(\x08\"&\n\tChainInfo\x12\x19\n\x05nodes\x18\x01 \x03(\x0b\x32\n.ChainNode2I\n\tDataStore\x12\x1d\n\x03Get\x12\t.KeyValue\x1a\t.KeyValue\"\x00\x12\x1d\n\x03Put\x12\t.KeyValue\x1a\t.KeyValue\"\x00\x32^\n\x10ReplicationChain\x12$\n\nForwardPut\x12\t.KeyValue\x1a\t.KeyValue\"\x00\x12$\n\nForwardGet\x12\t.KeyValue\x1a\t.KeyValue\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_store_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=20
  _KEYVALUE._serialized_end=58
  _NODEINFO._serialized_start=60
  _NODEINFO._serialized_end=101
  _CHAINNODE._serialized_start=103
  _CHAINNODE._serialized_end=173
  _CHAININFO._serialized_start=175
  _CHAININFO._serialized_end=213
  _DATASTORE._serialized_start=215
  _DATASTORE._serialized_end=288
  _REPLICATIONCHAIN._serialized_start=290
  _REPLICATIONCHAIN._serialized_end=384
# @@protoc_insertion_point(module_scope)
